trino:
  image:
    repository: trinodb/trino
    tag: "472"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    httpsPort: 8443
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  hostAliases:
    - ip: "127.0.0.1"
      hostnames:
        - "host.docker.internal"
