apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-trino
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-trino
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-trino
    spec:
      containers:
        - name: trino
          image: "{{ .Values.trino.image.repository }}:{{ .Values.trino.image.tag }}"
          imagePullPolicy: {{ .Values.trino.image.pullPolicy }}
          env:
            - name: TRINO_HOME
              value: "/etc/trino"
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.trino.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: config-volume
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: config-volume
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: config-volume
              mountPath: /etc/trino/password-authenticator.properties
              subPath: password-authenticator.properties
            - name: security-volume
              mountPath: /etc/trino/private_key.pem
              subPath: private_key.pem
            - name: security-volume
              mountPath: /etc/trino/pwd.db
              subPath: pwd.db
            - name: catalog-volume
              mountPath: /etc/trino/catalog
      volumes:
        - name: config-volume
          configMap:
            name: trino-config
        - name: security-volume
          configMap:
            name: trino-security
        - name: catalog-volume
          configMap:
            name: trino-catalog
