apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-trino
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  type: {{ .Values.trino.service.type }}
  ports:
    - port: {{ .Values.trino.service.httpsPort }}
      targetPort: 8443
      nodePort: 30443
      protocol: TCP
      name: https
  selector:
    app: {{ .Release.Name }}-trino
